/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_spc.h"
#include "fsl_vref.h"
#include "fsl_lpadc.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for GPIO4 peripheral */
#define GPIO4_GPIO GPIO4
/* Alias for PORT4 */
#define GPIO4_PORT PORT4
/* GPIO4 interrupt vector ID (number). */
#define GPIO4_INT_0_IRQN GPIO40_IRQn
/* GPIO4 interrupt handler identifier. */
#define GPIO4_INT_0_IRQHANDLER GPIO40_IRQHandler
/* Alias for GPIO3 peripheral */
#define GPIO3_GPIO GPIO3
/* Alias for PORT3 */
#define GPIO3_PORT PORT3
/* GPIO3 interrupt vector ID (number). */
#define GPIO3_INT_0_IRQN GPIO30_IRQn
/* GPIO3 interrupt handler identifier. */
#define GPIO3_INT_0_IRQHANDLER GPIO30_IRQHandler
/* GPIO3 interrupt vector ID (number). */
#define GPIO3_INT_1_IRQN GPIO31_IRQn
/* GPIO3 interrupt handler identifier. */
#define GPIO3_INT_1_IRQHANDLER GPIO31_IRQHandler
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Command 2 - TH */
#define ADC0_TH 2U
/* Command 3 - LIGHT_SENSOR */
#define ADC0_LIGHT_SENSOR 3U
/* Command 1 - POT */
#define ADC0_POT 1U
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 150000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 7UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER0_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER0 interrupt vector ID (number). */
#define CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 150000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 7UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER1_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER1 interrupt vector ID (number). */
#define CTIMER1_TIMER_IRQN CTIMER1_IRQn
/* Alias for GPIO0 peripheral */
#define GPIO0_GPIO GPIO0
/* Alias for PORT0 */
#define GPIO0_PORT PORT0
/* GPIO0 interrupt vector ID (number). */
#define GPIO0_INT_0_IRQN GPIO00_IRQn
/* GPIO0 interrupt handler identifier. */
#define GPIO0_INT_0_IRQHANDLER GPIO00_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[3];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[3];
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_0_config;
extern const ctimer_config_t CTIMER1_config;
extern const ctimer_match_config_t CTIMER1_Match_0_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void ctimer1_match_callback(uint32_t flags);
extern ctimer_callback_t CTIMER0_callback[];
  /* Single callback function declaration */
extern void ctimer2_match_callback(uint32_t flags);
extern ctimer_callback_t CTIMER1_callback[];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
