/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 25.09.10
board: FRDM-MCXN947
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: bcd6a5d9-2ca0-4565-92b9-b6861004d7cd
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO4'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO4'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO40_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'PORT_EFT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO4_init(void) {
  /* Make sure, the clock gate for port 4 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO4_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO4_INT_0_IRQN);
}

/***********************************************************************************************************************
 * GPIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO3'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO3'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO30_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'true'
    - gpio_interrupt_1:
      - IRQn: 'GPIO31_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'PORT_EFT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO3_init(void) {
  /* Make sure, the clock gate for port 3 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO3_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO3_INT_0_IRQN);
  /* Enable interrupt GPIO3_INT_1_IRQN request in the NVIC */
  EnableIRQ(GPIO3_INT_1_IRQN);
}

/***********************************************************************************************************************
 * VREF0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'VREF0'
- type: 'vref_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'vref_1_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'VREF0'
- config_sets:
  - fsl_vref:
    - vref_config:
      - bufferMode: 'kVREF_ModeHighPowerBuffer'
      - enableLowPowerBuff: 'true'
      - enableInternalVoltageRegulator: 'true'
      - enableChopOscillator: 'true'
      - enableHCBandgap: 'true'
      - enableCurvatureCompensation: 'true'
      - initTrim: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const vref_config_t VREF0_config = {
  .bufferMode = kVREF_ModeHighPowerBuffer,
  .enableLowPowerBuff = true,
  .enableInternalVoltageRegulator = true,
  .enableChopOscillator = true,
  .enableHCBandgap = true,
  .enableCurvatureCompensation = true
};

static void VREF0_init(void) {
  /* Power up analog module in SPC */
  SPC_EnableActiveModeAnalogModules(SPC0, kSPC_controlVref);
  /* VREF0 peripheral initialization */
  VREF_Init(VREF0_PERIPHERAL, &VREF0_config);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage1'
      - offsetCalibration: 'no'
      - autoCalibrate: 'false'
      - enableAnalogPreliminary: 'false'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt1'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_ConvPreemptImmediatelyNotAutoResumed'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig:
      - 0:
        - user_commandId: 'TH'
        - commandId: '2'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.3'
        - enableChannelB_b: 'false'
        - channelBNumber: 'B.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 1:
        - user_commandId: 'LIGHT_SENSOR'
        - commandId: '3'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideB'
        - channelNumber: 'B.0'
        - enableChannelB_b: 'false'
        - channelBNumber: 'B.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
      - 2:
        - user_commandId: 'POT'
        - commandId: '1'
        - chainedNextCommandNumber: '0'
        - sampleChannelMode: 'kLPADC_SampleChannelSingleEndSideA'
        - channelNumber: 'A.0'
        - enableChannelB_b: 'false'
        - channelBNumber: 'B.0'
        - enableAutoChannelIncrement: 'false'
        - loopCount: '0'
        - hardwareAverageMode: 'kLPADC_HardwareAverageCount1'
        - sampleTimeMode: 'kLPADC_SampleTimeADCK3'
        - hardwareCompareMode: 'kLPADC_HardwareCompareDisabled'
        - hardwareCompareValueHigh: '0'
        - hardwareCompareValueLow: '0'
        - conversionResoultuionMode: 'kLPADC_ConversionResolutionStandard'
        - enableWaitTrigger: 'false'
    - lpadcConvTriggerConfig:
      - 0:
        - user_triggerId: ''
        - triggerId: '0'
        - targetCommandId: '1'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '0'
        - channelBFIFOSelect: '0'
        - enableHardwareTrigger: 'false'
      - 1:
        - user_triggerId: ''
        - triggerId: '1'
        - targetCommandId: '2'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '1'
        - channelBFIFOSelect: '1'
        - enableHardwareTrigger: 'false'
      - 2:
        - user_triggerId: ''
        - triggerId: '2'
        - targetCommandId: '3'
        - delayPower: '0'
        - priority: 'false'
        - channelAFIFOSelect: '1'
        - channelBFIFOSelect: '1'
        - enableHardwareTrigger: 'false'
    - IRQ_cfg:
      - interrupt_type: ''
      - enable_irq: 'false'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage1,
  .enableAnalogPreliminary = false,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt1,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_ConvPreemptImmediatelyNotAutoResumed,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 0UL
};
lpadc_conv_command_config_t ADC0_commandsConfig[3] = {
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 3U,
    .channelBNumber = 0U,
    .chainedNextCommandNumber = 0,
    .enableChannelB = false,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideB,
    .channelNumber = 0U,
    .channelBNumber = 0U,
    .chainedNextCommandNumber = 0,
    .enableChannelB = false,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  },
  {
    .sampleChannelMode = kLPADC_SampleChannelSingleEndSideA,
    .channelNumber = 0U,
    .channelBNumber = 0U,
    .chainedNextCommandNumber = 0,
    .enableChannelB = false,
    .enableAutoChannelIncrement = false,
    .loopCount = 0UL,
    .hardwareAverageMode = kLPADC_HardwareAverageCount1,
    .sampleTimeMode = kLPADC_SampleTimeADCK3,
    .hardwareCompareMode = kLPADC_HardwareCompareDisabled,
    .hardwareCompareValueHigh = 0UL,
    .hardwareCompareValueLow = 0UL,
    .conversionResolutionMode = kLPADC_ConversionResolutionStandard,
    .enableWaitTrigger = false
  }
};
lpadc_conv_trigger_config_t ADC0_triggersConfig[3] = {
  {
    .targetCommandId = 1,
    .delayPower = 0UL,
    .channelAFIFOSelect = 0,
    .channelBFIFOSelect = 0,
    .priority = 1,
    .enableHardwareTrigger = false
  },
  {
    .targetCommandId = 2,
    .delayPower = 0UL,
    .channelAFIFOSelect = 1,
    .channelBFIFOSelect = 1,
    .priority = 1,
    .enableHardwareTrigger = false
  },
  {
    .targetCommandId = 3,
    .delayPower = 0UL,
    .channelAFIFOSelect = 1,
    .channelBFIFOSelect = 1,
    .priority = 1,
    .enableHardwareTrigger = false
  }
};

static void ADC0_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
  /* Configure conversion command 2. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, ADC0_TH, &ADC0_commandsConfig[0]);
  /* Configure conversion command 3. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, ADC0_LIGHT_SENSOR, &ADC0_commandsConfig[1]);
  /* Configure conversion command 1. */
  LPADC_SetConvCommandConfig(ADC0_PERIPHERAL, ADC0_POT, &ADC0_commandsConfig[2]);
  /* Configure trigger 0. */
  LPADC_SetConvTriggerConfig(ADC0_PERIPHERAL, 0, &ADC0_triggersConfig[0]);
  /* Configure trigger 1. */
  LPADC_SetConvTriggerConfig(ADC0_PERIPHERAL, 1, &ADC0_triggersConfig[1]);
  /* Configure trigger 2. */
  LPADC_SetConvTriggerConfig(ADC0_PERIPHERAL, 2, &ADC0_triggersConfig[2]);
}

/***********************************************************************************************************************
 * CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER0'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '150'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'true'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer1_match_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};
const ctimer_match_config_t CTIMER0_Match_0_config = {
  .matchValue = 149,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = true
};
/* Single callback functions definition */
ctimer_callback_t CTIMER0_callback[] = {ctimer1_match_callback};

static void CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER0_PERIPHERAL, &CTIMER0_config);
  /* Match channel 0 of CTIMER0 peripheral initialization */
  CTIMER_SetupMatch(CTIMER0_PERIPHERAL, CTIMER0_MATCH_0_CHANNEL, &CTIMER0_Match_0_config);
  CTIMER_RegisterCallBack(CTIMER0_PERIPHERAL, CTIMER0_callback, kCTIMER_SingleCallback);
}

/***********************************************************************************************************************
 * CTIMER1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER1'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER1'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'custom:150 MHz'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '300000000'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'true'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER1_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_SingleCallback'
      - singleCallback: 'ctimer2_match_callback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER1_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};
const ctimer_match_config_t CTIMER1_Match_0_config = {
  .matchValue = 299999999,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = true
};
/* Single callback functions definition */
ctimer_callback_t CTIMER1_callback[] = {ctimer2_match_callback};

static void CTIMER1_init(void) {
  /* CTIMER1 peripheral initialization */
  CTIMER_Init(CTIMER1_PERIPHERAL, &CTIMER1_config);
  /* Match channel 0 of CTIMER1 peripheral initialization */
  CTIMER_SetupMatch(CTIMER1_PERIPHERAL, CTIMER1_MATCH_0_CHANNEL, &CTIMER1_Match_0_config);
  CTIMER_RegisterCallBack(CTIMER1_PERIPHERAL, CTIMER1_callback, kCTIMER_SingleCallback);
}

/***********************************************************************************************************************
 * GPIO0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO0'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO0'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO00_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO0_init(void) {
  /* Make sure, the clock gate for port 0 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO0_INT_0_IRQN request in the NVIC */
  EnableIRQ(GPIO0_INT_0_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  GPIO4_init();
  GPIO3_init();
  VREF0_init();
  ADC0_init();
  CTIMER0_init();
  CTIMER1_init();
  GPIO0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
