/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/J23[4]/D16[5]/J22[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO/J23[2]/D16[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT1_2 (coord C4), P1_2/SJ4[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_10 (coord B12), P0_10/SJ5[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_23 (coord B7), P0_23/SJ9[1]/SW2[3]/SW2[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT2_7 (coord L2), P2_7/TP23/J12[1]/J3[13]/SJ3[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED8_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED8_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define SHIELD_LED8_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define SHIELD_LED8_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED8_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED8_PIN 7U                   /*!<@brief PORT pin number */
#define SHIELD_LED8_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT2_5 (coord K1), P2_5/TP25/J12[3]/J3[9]/SJ6[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED7_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED7_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define SHIELD_LED7_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define SHIELD_LED7_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED7_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED7_PIN 5U                   /*!<@brief PORT pin number */
#define SHIELD_LED7_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT2_2 (coord H3), P2_2/TP5/J12[8]/J3[7]/SJ7[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED6_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED6_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define SHIELD_LED6_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define SHIELD_LED6_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED6_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED6_PIN 2U                   /*!<@brief PORT pin number */
#define SHIELD_LED6_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT2_4 (coord K3), P2_4/TP26/J12[5]/J3[11]/SJ5[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED5_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED5_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define SHIELD_LED5_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define SHIELD_LED5_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED5_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED5_PIN 4U                   /*!<@brief PORT pin number */
#define SHIELD_LED5_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT0_22 (coord B8), P0_22/J4[8]/SJ18[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define SHIELD_LED2_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define SHIELD_LED2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED2_PIN 22U                   /*!<@brief PORT pin number */
#define SHIELD_LED2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT4_12 (coord T6), P4_12/SJ25[1]/J8[17]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED1_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define SHIELD_LED1_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define SHIELD_LED1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED1_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED1_PIN 12U                   /*!<@brief PORT pin number */
#define SHIELD_LED1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT0_15 (coord G13), P0_15/SJ8[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED3_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED3_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define SHIELD_LED3_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define SHIELD_LED3_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED3_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED3_PIN 15U                   /*!<@brief PORT pin number */
#define SHIELD_LED3_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT0_14 (coord E11), P0_14/J4[6]/SJ19[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_LED4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_LED4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define SHIELD_LED4_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define SHIELD_LED4_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_LED4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_LED4_PIN 14U                   /*!<@brief PORT pin number */
#define SHIELD_LED4_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_InitLEDsPins(void);

#define ICR_IRQS_irqs0 0x00u /*!<@brief Interrupt Select: Interrupt, trigger output, or DMA request 0 */
#define PCR_IBE_ibe1 0x01u   /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT4_13 (coord T7), P4_13/SJ10[1]/SJ2[3]/J8[18]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_SW1_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_SW1_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define SHIELD_SW1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_SW1_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define SHIELD_SW1_PIN 13U                   /*!<@brief PORT pin number */
#define SHIELD_SW1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT3_16 (coord J15), P3_16/SJ11[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_SW2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_SW2_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define SHIELD_SW2_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_SW2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_SW2_PIN 16U                   /*!<@brief PORT pin number */
#define SHIELD_SW2_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT0_29 (coord F8), P0_29/J1[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_SW3_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_SW3_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define SHIELD_SW3_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_SW3_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_SW3_PIN 29U                   /*!<@brief PORT pin number */
#define SHIELD_SW3_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT3_20 (coord M17), P3_20/J6[6]/J1[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_SW4_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_SW4_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define SHIELD_SW4_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_SW4_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_SW4_PIN 20U                   /*!<@brief PORT pin number */
#define SHIELD_SW4_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_18 (coord K16), P3_18/J1[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_NAV_A_LEFT_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_NAV_A_LEFT_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define SHIELD_NAV_A_LEFT_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_NAV_A_LEFT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_NAV_A_LEFT_PIN 18U                   /*!<@brief PORT pin number */
#define SHIELD_NAV_A_LEFT_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT1_23 (coord M4), P1_23/J9[23]/SJ1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_NAV_B_RIGHT_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_NAV_B_RIGHT_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define SHIELD_NAV_B_RIGHT_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_NAV_B_RIGHT_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define SHIELD_NAV_B_RIGHT_PIN 23U                   /*!<@brief PORT pin number */
#define SHIELD_NAV_B_RIGHT_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_17 (coord K15), P3_17/J1[11]/SJ10[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_NAV_C_UP_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_NAV_C_UP_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define SHIELD_NAV_C_UP_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_NAV_C_UP_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_NAV_C_UP_PIN 17U                   /*!<@brief PORT pin number */
#define SHIELD_NAV_C_UP_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT0_30 (coord E7), P0_30/SJ2[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_NAV_D_DOWN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_NAV_D_DOWN_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define SHIELD_NAV_D_DOWN_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_NAV_D_DOWN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_NAV_D_DOWN_PIN 30U                   /*!<@brief PORT pin number */
#define SHIELD_NAV_D_DOWN_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT2_6 (coord K2), P2_6/TP24/J12[2]/J3[15]/SJ1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_NAV_BUTTON_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_NAV_BUTTON_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define SHIELD_NAV_BUTTON_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_NAV_BUTTON_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_NAV_BUTTON_PIN 6U                   /*!<@brief PORT pin number */
#define SHIELD_NAV_BUTTON_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_NAVSwitchPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT2_0 (coord H2), P2_0/J3[1]/SJ8[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_1_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_1_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_1_PIN 0U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT1_22 (coord L4), P1_22/J9[24]/J3[3]/SJ9[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_2_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_2_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_2_PIN 22U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT2_3 (coord J3), P2_3/TP4/J12[7]/J3[5]/SJ4[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_3_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_3_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_3_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_3_PIN 3U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_4_GPIO_PIN 24U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_4_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_4_PIN 24U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_4_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT1_12 (coord D2), P1_12/J2[11]/J9[28]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_5_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_5_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_5_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_5_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_5_PIN 12U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_5_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_6_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_6_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_6_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_6_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_6_PIN 26U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_6_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT0_19 (coord C9), P0_19/J2[13]/J7[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_7_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_7_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_7_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_7_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_7_PIN 19U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_7_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT0_25 (coord A6), P0_25/J2[12]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_DIP_8_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_DIP_8_GPIO_PIN 25U              /*!<@brief GPIO pin number */
#define SHIELD_DIP_8_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_DIP_8_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_DIP_8_PIN 25U                   /*!<@brief PORT pin number */
#define SHIELD_DIP_8_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_DIPSwitchPins(void);

#define ICR_IRQS_irqs1 0x01u /*!<@brief Interrupt Select: Interrupt, trigger output, or DMA request 1 */
#define PCR_IBE_ibe1 0x01u   /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_31 (coord D7), P0_31/J1[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_ROTARY_BUTTON_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_ROTARY_BUTTON_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define SHIELD_ROTARY_BUTTON_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_ROTARY_BUTTON_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define SHIELD_ROTARY_BUTTON_PIN 31U                   /*!<@brief PORT pin number */
#define SHIELD_ROTARY_BUTTON_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_19 (coord K17), P3_19/J5[1]/J1[13]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_ROTARY_1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_ROTARY_1_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define SHIELD_ROTARY_1_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_ROTARY_1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_ROTARY_1_PIN 19U                   /*!<@brief PORT pin number */
#define SHIELD_ROTARY_1_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT3_21 (coord L16), P3_21/J6[4]/J1[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define SHIELD_ROTARY_2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define SHIELD_ROTARY_2_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define SHIELD_ROTARY_2_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define SHIELD_ROTARY_2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define SHIELD_ROTARY_2_PIN 21U                   /*!<@brief PORT pin number */
#define SHIELD_ROTARY_2_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_RotaryPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SHIELD_ADCPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPI2C2_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/